# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'John-Craig Borman'
tagline:          'Aspiring Quant'
description:      'Quantitative Researcher and Developer'
base:             /

author:
  name:           'John-Craig Borman'
  url:            https://www.linkedin.com/in/jcborman/
  icon:           /public/img/icon.png

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/bormanjo/bormanjo.github.io

# Plugins
plugins:
  - jekyll-gist
  - jekyll-paginate
